services:
  - type: worker
    runtime: node
    name: typedtrader
    repo: https://github.com/bennycode/trading-signals
    numInstances: 1
    region: frankfurt
    plan: starter
    branch: main
    buildCommand: npm install && npx lerna run dist
    startCommand: npm run start:bot
    envVars:
      - key: TYPEDTRADER_DB_DIRECTORY
        value: '/var/data'
      - key: TYPEDTRADER_DB_ENCRYPTION_KEY
        sync: false
      - key: XMTP_WALLET_KEY
        sync: false
      - key: XMTP_DB_ENCRYPTION_KEY
        sync: false
      - key: XMTP_DB_DIRECTORY
        value: '/var/data'
      - key: XMTP_ENV
        value: 'production'
    disk:
      name: data
      mountPath: /var/data
      sizeGB: 1
